kind: pipeline
type: docker # exec, ssh ,kubernetes
name: default

steps:
  - name: greeting0
    image: alpine
    settings:
      repo: octocat/hello-world
      username:
        from_secret: password
      password:
        from_secret: password
    environment:
      USERNAME:
        from_secret: password
      PASSWORD:
        from_secret: password
    commands:
      - echo hello
      - echo world
      - echo $USERNAME
      - ls -al
  - name: build
    image: golang
    commands:
      - go env
      - go version
# ---
# kind: pipeline
# type: exec
# name: default

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: greeting1
#   commands:
#   - echo hello world

# ---
# kind: pipeline
# type: ssh
# name: default

# server:
#   host: ww.asppj.top
#   user: root
#   password:
#     from_secret: password

# steps:
# - name: greeting2
#   commands:
#   - echo hello world

# ---
# kind: pipeline
# type: docker
# name: backend

# steps:
# - name: build
#   image: golang
#   commands:
#   - go build
#   - go test

# ---
# kind: pipeline
# type: docker
# name: frontend

# steps:
# - name: build
#   image: node
#   commands:
#   - npm install
#   - npm test

# ---
# kind: pipeline
# name: after

# steps:
# - name: notify
#   image: plugins/slack
#   settings:
#     room: general
#     webhook: https://www.baidu.com

# depends_on:
# - backend
# - frontend
